[package]
name = "maelstrom-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
maelstrom-rust-derive = { path = "../maelstrom-rust-derive" }
